Enhance docker clean up in CI (#1442)
* enhance docker clean up
* clean up invalid label

Signed-off-by: chensuyue <suyue.chen@intel.com>
Signed-off-by: jilongwa <jilong.wang@intel.com>

diff --git a/.github/workflows/pr-microservice-test.yml b/.github/workflows/pr-microservice-test.yml
--- a/.github/workflows/pr-microservice-test.yml
+++ b/.github/workflows/pr-microservice-test.yml
@@ -35,10 +35,20 @@ jobs:
     steps:
       - name: Clean Up Working Directory
         run: |
+          # clean up workspace
           sudo rm -rf ${{github.workspace}}/*
+
+          # clean up test containers
           cid=$(docker ps -aq --filter "name=test-comps-*")
           if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
+          # clean up containers use ports
+          cid=$(docker ps --format '{{.Names}} : {{.Ports}}' | grep -v ' : $' | awk -F' : ' '{print $1}')
+          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
+
+          # clean up images
           docker rmi $(docker images --filter reference="*/*:comps" -q) || true
+          docker rmi $(docker images --filter reference="opea/*:*" -q) || true
+
           docker system prune -f
           docker ps
 
@@ -69,10 +79,17 @@ jobs:
           timeout 60m bash $(find . -type f -name test_${service}.sh)
 
       - name: Clean up container
+        if: cancelled() || failure()
         run: |
+          # clean up test containers
           cid=$(docker ps -aq --filter "name=test-comps-*")
           if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
+          # clean up containers use ports
+          cid=$(docker ps --format '{{.Names}} : {{.Ports}}' | grep -v ' : $' | awk -F' : ' '{print $1}')
+          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid && sleep 1s; fi
+
           docker system prune -f
+          docker ps
 
       - name: Publish pipeline artifact
         if: ${{ !cancelled() }}
